#
# :-S   Do we have to edit the build.yml AND set a git tag (label) to trigger the github build to pick up the new git tag / label?!
# --> nope. The label has to match the format specified below: major.minor.rev. I previously expected it to be a real regex, but it ain't; the '.' is a literal '.' always.
#

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.*'
    paths:
      - '.github/workflows/**'
      - '*.sfd'
      - '*.py'
      - '*.sh'

# fontforge -c 'Open($1); Generate($2)' foo.sfd foo.ttf
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        echo "Check that the helper script add-apt-repository is installed"
        sudo apt-get install software-properties-common
        echo "Add the FontForge PPA (which will also add the authentication key)"
        sudo add-apt-repository ppa:fontforge/fontforge
        echo "Update the software list to include packages from the PPA"
        sudo apt-get update
        echo "Install FontForge"
        sudo apt-get install fontforge
    - run: ./build_ttf.sh
    - run: echo "hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - name: "Offer upload artifact (fonts ZIP file) for download"
      uses: actions/upload-artifact@main
      with:
        name: 3270font_${{ env.hash }}
        path: distr
